//---------------------------------------------------------------
//        Go4 Framework release package V.1.0000 
//                      24-May-2002
//---------------------------------------------------------------
//	 The GSI Online Offline Object Oriented (Go4) Project
//	 Experiment Data Processing at DVEE department, GSI
//---------------------------------------------------------------
//
//Copyright (C) 2000- Gesellschaft f. Schwerionenforschung, GSI
//                    Planckstr. 1, 64291 Darmstadt, Germany
//Contact:            http://go4.gsi.de
//----------------------------------------------------------------
//This software can be used under the license agreements as stated
//in Go4License.txt file which is part of the distribution.
//----------------------------------------------------------------
/* Generated by Together */

#ifdef NOGO4


#include "TGalileoEventFactory.h"

TGalileoEventFactory::TGalileoEventFactory(std::string  name)
: TGo4EventServerFactory(name)
{

}

TGalileoEventFactory::TGalileoEventFactory() 
: TGo4EventServerFactory("EB Event Factory")
{ 

}

TGalileoEventFactory::~TGalileoEventFactory() 
{ 

}

TGo4EventProcessor * TGalileoEventFactory::CreateEventProcessor(TGo4EventProcessorParameter* par)
{ 

// note: parameter is not yet used here
   TGalileoEventProcessor* ebproc = new TGalileoEventProcessor;
	/* 14.08.01 EL   
   std::cout << "TGalileoEventFactory: creating ebevent processor"<< std::endl;
	*/
   return ebproc;


}

TGo4EventElement * TGalileoEventFactory::CreateOutputEvent()
{ 
  std::cout << "Ever useed ???" <<std::endl;
   TGalileoEvent * ebevent = new TGalileoEvent();
//   fxEbEvent = new TGalileoEvent();
	/* 14.08.01 EL   
   std::cout << "TGalileoEventFactory: creating output event "<< ebevent->ClassName() << std::endl;
	*/
   SetOutputEvent(ebevent); // important for some event store implementations!!!
   return ebevent;


}

ClassImp(TGalileoEventFactory)
#endif 
